2025-06-10 14:08:19 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:08:19 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:08:19 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:08:20 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:08:20 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:08:20 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:08:20 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:08:20 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:08:22 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:08:23 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:08:23 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:08:23 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:08:23 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:09:03 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:09:03 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:13:55 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:14:04 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:14:04 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:14:04 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:14:06 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:14:46 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:14:48 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:14:51 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 361, in evolve_solution
    evolved_individual = self.llm.sample_solution(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 106, in sample_solution
    message = self.query(session_messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llm.py", line 277, in query
    response = chat_session.send_message(last["content"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 578, in send_message
    response = self.model.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 835, in generate_content
    response = rpc(
               ^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target
    next_sleep = _retry_error_helper(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/miniconda3/envs/eoh/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
]
.
2025-06-10 14:14:58 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:14:59 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:15:00 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:15:01 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:15:08 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:15:09 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:15:10 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:15:10 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:15:11 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:15:52 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:20:45 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:20:45 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
