2025-06-10 14:02:05 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:02:06 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:02:06 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:02:07 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:02:08 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:02:08 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:02:08 ERROR Can not run the algorithm
2025-06-10 14:02:08 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:02:08 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:02:10 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:02:10 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:02:10 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:02:11 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:02:11 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:08:08 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
2025-06-10 14:08:16 INFO --- GNBG Problem Parameters for f1 ---
  Dimension: 30, MaxEvals: 500000
  Search Bounds: [-100, 100]
  Number of Components: 1
  Known Optimum Value: -1081.983799
  Lambda (Curvature): [1]
  Mu (Asymmetry/Depth): [0 0]
----------------------------------------
2025-06-10 14:08:17 INFO An exception occured: Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 365, in evolve_solution
    evolved_individual = self.evaluate_fitness(evolved_individual)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea/llamea.py", line 248, in evaluate_fitness
    updated_individual = self.f(individual, self.logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/llamea_gnbg_run_test_v2.py", line 89, in evaluateGNBG
    current_run_aocc = calculate_aocc_from_gnbg_history(fe_history=problem.FEhistory,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/calc_aocc_from_gnbg.py", line 33, in calculate_aocc_from_gnbg_history
    for error_at_fe in best_error_history_at_fe[:budget_B]: # Ensure we only consider up to budget_B
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
.
